"use client";

// Executive Narratives — the brief a leader reads, not a dashboard they decode.
// A written, periodized story (weekly / monthly / quarterly) composed live from
// the engines: the situation, what changed, what to do, risk posture, and the
// accountability section ("are we getting smarter?"). Deterministic prose over
// real numbers — every sentence is grounded, none is generated by an LLM.

import { useState } from "react";
import { cn } from "@/lib/utils";
import { useNarrative, type NarrativePeriod } from "@/lib/hooks/use-executive";
import { CalendarDays, FileText } from "lucide-react";

const PERIODS: { id: NarrativePeriod; label: string }[] = [
  { id: "weekly", label: "Weekly Brief" },
  { id: "monthly", label: "Monthly Review" },
  { id: "quarterly", label: "Quarterly Strategy" },
];

export default function NarrativesPage() {
  const [period, setPeriod] = useState<NarrativePeriod>("weekly");
  const narrative = useNarrative(period);

  return (
    <div className="space-y-6">
      {/* Period switcher */}
      <div className="flex items-center gap-2">
        <div className="inline-flex rounded-xl border border-line bg-ink-surface p-1">
          {PERIODS.map((p) => (
            <button
              key={p.id}
              onClick={() => setPeriod(p.id)}
              aria-pressed={period === p.id}
              className={cn(
                "flex items-center gap-2 rounded-lg px-3.5 py-1.5 text-sm font-semibold transition-colors",
                period === p.id ? "bg-brand text-[#04281A]" : "text-fg-secondary hover:text-fg"
              )}
            >
              <CalendarDays size={14} /> {p.label}
            </button>
          ))}
        </div>
      </div>

      {narrative.isLoading && (
        <div className="space-y-4">
          <div className="panel h-40 animate-pulse" />
          <div className="panel h-64 animate-pulse" />
        </div>
      )}

      {narrative.isError && (
        <div className="panel flex flex-col items-start gap-3 p-8">
          <div className="text-lg font-semibold text-danger">Couldn&apos;t compose the brief</div>
          <p className="text-sm text-fg-muted">{(narrative.error as Error)?.message}</p>
          <button onClick={() => narrative.refetch()} className="rounded-lg bg-brand px-4 py-2 text-sm font-bold text-[#04281A]">Retry</button>
        </div>
      )}

      {narrative.data && (
        <article className="mx-auto max-w-3xl">
          {/* Masthead */}
          <header className="panel relative overflow-hidden p-8">
            <div className="flex items-center gap-2 text-fg-muted">
              <FileText size={15} />
              <span className="label-xs">{narrative.data.title}</span>
            </div>
            <h1 className="mt-3 font-display text-3xl font-bold leading-tight tracking-tight">
              {narrative.data.headline}
            </h1>
            <p className="mt-4 border-l-2 border-brand/50 pl-3 text-sm italic text-fg-muted">
              Confidence: {narrative.data.confidence}
            </p>
          </header>

          {/* Sections — reads like a memo */}
          <div className="mt-6 space-y-6">
            {narrative.data.sections.map((s, i) => (
              <section key={s.heading} className="panel p-6">
                <div className="flex items-baseline gap-3">
                  <span className="font-mono text-sm text-brand">{String(i + 1).padStart(2, "0")}</span>
                  <h2 className="font-display text-xl font-bold tracking-tight">{s.heading}</h2>
                </div>
                <p className="mt-3 text-base leading-7 text-fg-secondary">{s.body}</p>
                {s.bullets && s.bullets.length > 0 && (
                  <ul className="mt-4 space-y-1.5 border-t border-line-subtle pt-4">
                    {s.bullets.map((b) => (
                      <li key={b} className="flex items-start gap-2.5 text-sm text-fg-secondary">
                        <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand/70" />
                        <span>{b}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </section>
            ))}
          </div>

          <p className="mt-6 text-center text-2xs text-fg-muted">
            Composed live from the intelligence engines · grounded, reproducible, no generated prose.
          </p>
        </article>
      )}
    </div>
  );
}
